In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim

# Part 1 : Perceptron Model

In [ ]:
and_data = pd.DataFrame (
    {
        'x1' : [0,0,1,1],
        'x2' : [0,1,0,1],
        'y' : [0,0,0,1]
    }
)

or_data = pd.DataFrame (
    {
        'x1' : [0,0,1,1],
        'x2' : [0,1,0,1],
        'y' : [0,1,1,1]
    }
)

nor_data = pd.DataFrame (
    {
        'x1' : [0,0,1,1],
        'x2' : [0,1,0,1],
        'y' : [1,0,0,0]
    }
)

In [ ]:
def step_function (x) :
    return torch.where(x >= 0, torch.tensor(1.0), torch.tensor(0.0))

class NeuralNetwork (nn.Module) :
    def __init__ (self) :
        super (NeuralNetwork, self).__init__()
        self.layer1 = nn.Linear (2, 1)

    def forward (self, x) :
        x = self.layer1 (x)
        x = step_function (x)
        return x

In [ ]:
model = NeuralNetwork()

inputs = torch.tensor(and_data[['x1', 'x2']].values, dtype=torch.float32)
labels = torch.tensor(and_data['y'].values.reshape(-1,1), dtype=torch.float32)

learning_rate = 0.1
epochs = 10

for epoch in range(epochs):
    total_loss = 0
    for x, y in zip(inputs, labels):
        output = model(x)
        error = y - output
        total_loss += error.abs().item()

        with torch.no_grad():
            model.layer1.weight += learning_rate * error * x
            model.layer1.bias += learning_rate * error

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss}")

print("\nPredictions:")
for x in inputs:
    output = model(x)
    print(f"Input: {x.tolist()} -> Output: {int(output.item())}")

Epoch 1/10, Loss: 3.0
Epoch 2/10, Loss: 3.0
Epoch 3/10, Loss: 2.0
Epoch 4/10, Loss: 2.0
Epoch 5/10, Loss: 2.0
Epoch 6/10, Loss: 1.0
Epoch 7/10, Loss: 0.0
Epoch 8/10, Loss: 0.0
Epoch 9/10, Loss: 0.0
Epoch 10/10, Loss: 0.0

Predictions:
Input: [0.0, 0.0] -> Output: 0
Input: [0.0, 1.0] -> Output: 0
Input: [1.0, 0.0] -> Output: 0
Input: [1.0, 1.0] -> Output: 1


In [ ]:
plt.plot()

In [ ]:
model = NeuralNetwork()

inputs = torch.tensor(or_data[['x1', 'x2']].values, dtype=torch.float32)
labels = torch.tensor(or_data['y'].values.reshape(-1,1), dtype=torch.float32)

learning_rate = 0.1
epochs = 10

for epoch in range(epochs):
    total_loss = 0
    for x, y in zip(inputs, labels):
        output = model(x)
        error = y - output
        total_loss += error.abs().item()

        with torch.no_grad():
            model.layer1.weight += learning_rate * error * x
            model.layer1.bias += learning_rate * error

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss}")

print("\nPredictions:")
for x in inputs:
    output = model(x)
    print(f"Input: {x.tolist()} -> Output: {int(output.item())}")

Epoch 1/10, Loss: 1.0
Epoch 2/10, Loss: 1.0
Epoch 3/10, Loss: 1.0
Epoch 4/10, Loss: 1.0
Epoch 5/10, Loss: 1.0
Epoch 6/10, Loss: 1.0
Epoch 7/10, Loss: 1.0
Epoch 8/10, Loss: 0.0
Epoch 9/10, Loss: 0.0
Epoch 10/10, Loss: 0.0

Predictions:
Input: [0.0, 0.0] -> Output: 0
Input: [0.0, 1.0] -> Output: 1
Input: [1.0, 0.0] -> Output: 1
Input: [1.0, 1.0] -> Output: 1


In [ ]:
model = NeuralNetwork()

inputs = torch.tensor(nor_data[['x1', 'x2']].values, dtype=torch.float32)
labels = torch.tensor(nor_data['y'].values.reshape(-1,1), dtype=torch.float32)

learning_rate = 0.1
epochs = 10

for epoch in range(epochs):
    total_loss = 0
    for x, y in zip(inputs, labels):
        output = model(x)
        error = y - output
        total_loss += error.abs().item()

        with torch.no_grad():
            model.layer1.weight += learning_rate * error * x
            model.layer1.bias += learning_rate * error

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss}")

print("\nPredictions:")
for x in inputs:
    output = model(x)
    print(f"Input: {x.tolist()} -> Output: {int(output.item())}")

Epoch 1/10, Loss: 3.0
Epoch 2/10, Loss: 3.0
Epoch 3/10, Loss: 2.0
Epoch 4/10, Loss: 1.0
Epoch 5/10, Loss: 0.0
Epoch 6/10, Loss: 0.0
Epoch 7/10, Loss: 0.0
Epoch 8/10, Loss: 0.0
Epoch 9/10, Loss: 0.0
Epoch 10/10, Loss: 0.0

Predictions:
Input: [0.0, 0.0] -> Output: 1
Input: [0.0, 1.0] -> Output: 0
Input: [1.0, 0.0] -> Output: 0
Input: [1.0, 1.0] -> Output: 0


In [ ]:
from sklearn.linear_model import Perceptron


X = and_data[['x1', 'x2']].values
y = and_data['y'].values

model_sklearn = Perceptron(random_state=0, max_iter=10, tol=1e-3)
model_sklearn.fit(X, y)

predictions_sklearn = model_sklearn.predict(X)

print("Predictions using scikit-learn Perceptron:")
for input_data, prediction in zip(X, predictions_sklearn):
    print(f"Input: {input_data.tolist()} -> Output: {prediction}")

Predictions using scikit-learn Perceptron:
Input: [0, 0] -> Output: 0
Input: [0, 1] -> Output: 0
Input: [1, 0] -> Output: 0
Input: [1, 1] -> Output: 1


/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_stochastic_gradient.py:738: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(


# Part 2 : Back Propagation

In [ ]:
class NeuralNetwork (nn.Module) :
    def __init__ (self) :
        super (NeuralNetwork, self).__init__()
        self.layer1 = nn.Linear (2, 2)
        self.layer2 = nn.Linear (2, 2)
        self.sigmoid = nn.Sigmoid()

    def forward (self, x) :
        x = self.layer1 (x)
        x = self.sigmoid (x)
        x = self.layer2 (x)
        x = self.sigmoid (x)
        return x

In [ ]:
inputs = torch.tensor([0.05, 0.1])
labels = torch.tensor([0.01, 0.99])

model = NeuralNetwork()

with torch.no_grad():
          model.layer1.weight.copy_(torch.tensor([[0.15, 0.20],
                                                  [0.25, 0.30]]))
          model.layer1.bias.copy_(torch.tensor([0.35, 0.35]))

          model.layer2.weight.copy_(torch.tensor([[0.40, 0.45],
                                                  [0.50, 0.55]]))
          model.layer2.bias.copy_(torch.tensor([0.60, 0.60]))

In [ ]:
model.train()

criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.2)

num_epochs = 10000
for epoch in range(num_epochs):

    outputs = model(inputs)
    loss = criterion(outputs, labels)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if (epoch+1) % 1000 == 0:
        print(f'Epoch: [{epoch+1}/{num_epochs}], Output:{outputs.detach()}, Loss: {loss.item():.6f}')

Epoch: [1000/10000], Output:tensor([0.0298, 0.9710]), Loss: 0.000376
Epoch: [2000/10000], Output:tensor([0.0246, 0.9759]), Loss: 0.000206
Epoch: [3000/10000], Output:tensor([0.0216, 0.9787]), Loss: 0.000131
Epoch: [4000/10000], Output:tensor([0.0196, 0.9806]), Loss: 0.000091
Epoch: [5000/10000], Output:tensor([0.0182, 0.9820]), Loss: 0.000066
Epoch: [6000/10000], Output:tensor([0.0172, 0.9830]), Loss: 0.000050
Epoch: [7000/10000], Output:tensor([0.0163, 0.9838]), Loss: 0.000039
Epoch: [8000/10000], Output:tensor([0.0156, 0.9845]), Loss: 0.000031
Epoch: [9000/10000], Output:tensor([0.0151, 0.9851]), Loss: 0.000025
Epoch: [10000/10000], Output:tensor([0.0146, 0.9855]), Loss: 0.000020


In [ ]:
print("Final Weights : ")
print(model.layer1.weight)
print(model.layer1.bias)
print(model.layer2.weight)
print(model.layer2.bias)

Final Weights : 
Parameter containing:
tensor([[0.1799, 0.2598],
        [0.2792, 0.3583]], requires_grad=True)
Parameter containing:
tensor([0.9477, 0.9331], requires_grad=True)
Parameter containing:
tensor([[-1.3792, -1.3324],
        [ 1.4530,  1.5039]], requires_grad=True)
Parameter containing:
tensor([-2.2410,  2.0704], requires_grad=True)
